lsst-epo/rubin-obs-api

- api/config/general.php
> Disabling "disabled" CORS header (enabling CORS)

- .github/workflows/push-dev-rubin-obs-api.yaml
> Adding back workflow that somehow got removed

- api/composer.lock
> Upgraded composer.lock file

- api/config/project/project.yaml
> Updated schema version to propogate DB changes

- README.md
- api/composer.json
- api/composer.lock
> Removed SQL dump file, added custom plugin, and

- .github/workflows/develop-push-gae.yaml
- .github/workflows/master-pr-gae.yaml
- .github/workflows/master-push-gae.yaml
- .github/workflows/master-tags.yaml
- README.md
- api/composer.json
- api/composer.lock
> Version name formatting

- api/config/project/fields/image--496e755e-78ab-4e3f-8c3a-9b320023b8ec.yaml
Use the DAMAsset type provided by the plugin for Callout images
> Use DAMAsset type

- api/config/project/project.yaml
> Removed git merge lines from project.yaml

- api/composer.json
- api/composer.lock
> Bumped DAM plugin version to pick up fix

- api/composer.json
- api/composer.lock
> Removed min version 'dev' from composer.json

- api/composer.json
- api/composer.lock
> Bumping DAM plugin version to get bug fix

- api/config/project/project.yaml
- api/config/project/users/groups/editors--01b89d98-9aa4-46d5-a9a0-60a0c07fd815.yaml
Gives the Editors user group access to the new Glossary Term and Investigation entry types.
> [C] Grant editors permissions for new entries

- api/composer.json
- api/composer.lock
> Upped DAM plugin version

- api/composer.json
- api/composer.lock
> Upped version of DAM plugin yet again

- api/config/project/fields/supportersLogosAlt--fea30fc7-fc92-4268-961f-d514c1b903b8.yaml
- api/config/project/globalSets/footer--1a2ba41a-3949-4982-9cb3-f8b03863bcfd.yaml
- api/config/project/project.yaml
Relates to https://github.com/lsst-epo/rubin-obs-client/issues/51
> [F] Add Supporters' Logo Alt to footer globals

- api/config/project/fields/dynamicComponent--fa690eba-6d46-4a5e-9dcd-0845f5b56c1b.yaml
- api/config/project/project.yaml
Relates to https://github.com/lsst-epo/rubin-obs-client/issues/19
> [F] Add options to Dynamic Component

- api/composer.json
- api/composer.lock
> Upped version of DAM plugin for new fix

- api/composer.json
- api/composer.lock
> Upped version for new troubleshooting

- api/composer.json
- api/composer.lock
> More troubleshooting DAM plugin version bump

- api/composer.json
- api/composer.lock
> DAM plugin ver. bump to grab bug fix

- api/composer.json
- api/composer.lock
- api/config/project/fields/contentImage--fb052686-4537-4fe5-9ce2-ff3fd4a341a2.yaml
- api/config/project/fields/damAsset--496e755e-78ab-4e3f-8c3a-9b320023b8ec.yaml
- api/config/project/fields/hero--05eead62-7bf9-43e4-a7e8-bcd8f9f77323.yaml
- api/config/project/fields/imageQuote--48ba11bd-90a5-4239-a24c-d44d01affbcf.yaml
- api/config/project/fields/staffTradingCard--1f7ad44a-de72-4538-9628-acdbc79e32f6.yaml
- api/config/project/project.yaml
Also includes Craft core and plugins upgrades to latest stable
> Content, Hero, Quote, and Trading Card image fields are localized

- .github/workflows/master-tags.yaml
- api/config/project/project.yaml
- api/config/project/users/groups/editors--01b89d98-9aa4-46d5-a9a0-60a0c07fd815.yaml
- Editors user group as permission to CRUD all content kinds of entries and globals
- DAM plugin uses env vars instead of hardcoded values
- Prod github workflow calls out "production" instead of "integration" in logs
> Odds and ends

- api/config/project/fields/text--7db205b7-a548-42f1-8c26-416ec51cf3fa.yaml
- api/config/project/matrixBlockTypes/tableCell--1c065033-f41d-4566-9863-d34a4bf24836.yaml
- api/config/project/matrixBlockTypes/tableRow--6908c928-e76b-4692-ae6f-e3d8c994d0ce.yaml
- api/config/project/project.yaml
- api/config/redactor/TableCellContent.json
- api/config/redactor/TextContentBlock.json
- api/config/redactor/plugins/textcolor.js
- fontcolors available in TextBlock, SimpleTable, and ComplexTable
> [EPO-6661] Misc updates based on Ed team feedback

- .gitignore
- README.md
- api/composer.json
- api/composer.lock
Includes minor changes to readme and gitignore
> Craft and Neo updates

- api/composer.json
- api/composer.lock
- api/config/project/matrixBlockTypes/item--e95d3769-cc6d-4366-85a1-a39780d0bc0e.yaml
- api/config/project/project.yaml
Includes minor composer packages updates
> Assets list target asset field is translatable

- api/config/project/entryTypes/post--4729ad5e-485e-4f98-995d-79fa5254cd42.yaml
- api/config/project/matrixBlockTypes/externalLink--9a5411c3-bbd7-4f75-a62a-498711e141e4.yaml
- api/config/project/matrixBlockTypes/textLink--31b350fb-6fbd-4533-b006-4c287f689ed3.yaml
- api/config/project/project.yaml
- Hero is optional
- Sidebar link text and target url are translatable
> News Post field updates

- api/composer.lock
> Forgot to check in composer.lock

- api/composer.lock
Upped DAM plugin to 0.3.1-alpha for bug fix
> [B] Downgrade deps to correct build error in craft core + plugins version mismatches

- .github/workflows/develop-pr-gae.yaml
- .gitignore
- api/config/project/fields/colorScheme--d7fc5f39-2426-421b-bd0b-10aadae80ae3.yaml
- api/config/project/fields/floatDirection--dc44e79d-b126-413d-bc02-0776d6ace2d1.yaml
- api/config/project/project.yaml
- api/plugins/nextbuilds/src/NextBuilds.php
- api/plugins/nextbuilds/src/services/Request.php
- Nextbuilds plugin has more events that trigger page rebuilds
- Nextbuilds only pushes messages to the Control Panel if there is a session to push them to
- ColorScheme dropdown includes a default option
- Content Image float direction is no longer translatable
- Preview branch has corrected GCP zone to deploy to
> Fix nextBuilds bug, dropdowns needing default value error, and preview branch workflow discrepancy

- api/composer.json
- api/composer.lock
> Up'd the DAM plugin version to v0.4.2

- api/config/general.php
EPO-8521 Override runQueueAutomatically default value for supervisord
> Override runQueueAutomatically default value

- api/composer.lock
> New DAM plugin version bump

- api/config/project/project.yaml
EPO-8795 - Change GCS plugin bucket names from choose to manual
> Change GCS plugin bucket names from choose to man

- .github/workflows/build-and-push.yaml
Replaces the environment determination logic with the correct logic that includes "dev" as the default environment
> More workflow fixes

- Makefile
Updated `Makefile` with DB scripts
> Updated `Makefile` with DB scripts

- api/config/app.php
> Updated AssetManager config

- Makefile
- README.md
- db/Dockerfile
Fixed `Makefile` and updated README.md with instructions
> Fixed `Makefile` and updated README.md with instrs

- api/config/project/entryTypes/person--5884a9c8-b8b4-48b4-872e-ba06c7fd7bd9.yaml
- api/config/project/fieldGroups/40914d25-1cae-448f-aeea-2d7d779d620d.yaml
- api/config/project/fields/people--66cc7887-85b3-4299-abf5-f92cbae50a8b.yaml
- api/config/project/fields/peopleLayout--57dcbdae-db2b-4f63-8d0e-26bdfb80c7db.yaml
- api/config/project/fields/personAffiliation--e6e1a190-5824-49c2-8242-ee637519925d.yaml
- api/config/project/graphql/schemas/4fe339ec-7579-46f4-a362-df6ee8de4b3c.yaml
- api/config/project/graphql/schemas/77dc755a-bb96-4422-b00f-c7d74e45d400.yaml
- api/config/project/graphql/schemas/d6898b26-bfa2-41d3-9e26-0092b2021762.yaml
- api/config/project/neo/orders/72e5075a-9b06-4674-b040-615f4a6f7b70.yaml
- api/config/project/neoBlockTypes/peopleBlock--9d7c57a1-0518-46c5-9c44-0fe5757e5b88.yaml
- api/config/project/project.yaml
- api/config/project/sections/people--7b6ae5d5-7819-48b3-b2ab-7f7109c3ebfa.yaml
**Related to**
https://github.com/lsst-epo/rubin-obs-client/pull/432
**What it Does**
Adds a People Entry type and a People Content Block available for page entries
**How to Test**
1. Create a handful of People entries, some with optional fields filled in, some without.
2. Add a People Content Block to a page
3. Save page entry and view on the frontend.  Expect no content block to render if no People have been added to the People Content Block
4. Add some Publications to the People Content Block
5. Save page entry and view on the frontend.  Expect content block to render now that it has People added
> [F] People Entries + People Content Block

- README.md
Updated `README.md` w/DB script context
> Updated `README.md` w/DB script context

- README.md
Fixed instruction text in `README.md`
> Fixed instruction text in `README.md`

- api/composer.json
- api/composer.lock
- api/plugins/nextbuilds/CHANGELOG.md
- api/plugins/nextbuilds/composer.json
- api/plugins/nextbuilds/src/NextBuilds.php
Revalidate occurs after DB update now
> Revalidate occurs after DB update now

- api/config/project/entryTypes/dataProduct--0bcfefd9-d36f-4fa2-bce3-53dbb423379b.yaml
- api/config/project/entryTypes/post--4729ad5e-485e-4f98-995d-79fa5254cd42.yaml
- api/config/project/fields/sidebarAssets--c11d26d4-236a-4b06-99f6-3a8f67821ada.yaml
- api/config/project/graphql/schemas/4fe339ec-7579-46f4-a362-df6ee8de4b3c.yaml
- api/config/project/matrixBlockTypes/externalLink--9a5411c3-bbd7-4f75-a62a-498711e141e4.yaml
- api/config/project/matrixBlockTypes/galleryItem--f456f3b4-70e5-4692-b114-31a9c47443e9.yaml
- api/config/project/matrixBlockTypes/header--afe3ef3c-add3-45cc-b88b-d01559eb7b32.yaml
- api/config/project/matrixBlockTypes/image--9b45a4e3-4461-43d1-881a-ef72029ba2ad.yaml
- api/config/project/matrixBlockTypes/textLink--31b350fb-6fbd-4533-b006-4c287f689ed3.yaml
- api/config/project/project.yaml
- api/config/project/sections/dataProducts--62e0ff8c-8f41-49ff-abc6-ce550e47f70b.yaml
> [F] Data products page

- api/plugins/nextbuilds/src/NextBuilds.php
Revert deprecated class fix after regression
> Revert deprecated class fix after regression

- api/config/project/graphql/schemas/4fe339ec-7579-46f4-a362-df6ee8de4b3c.yaml
- api/config/project/graphql/schemas/77dc755a-bb96-4422-b00f-c7d74e45d400.yaml
- api/config/project/graphql/schemas/d6898b26-bfa2-41d3-9e26-0092b2021762.yaml
- api/config/project/project.yaml
Add missing Callout - News + CST Editor accounts to schema
> fix(schema): add news callouts back to public schema

- api/plugins/nextbuilds/CHANGELOG.md
- api/plugins/nextbuilds/composer.json
- api/plugins/nextbuilds/src/NextBuilds.php
Correctly traversing Structures event object
> Correctly traversing Structures event object

- api/composer.json
- api/composer.lock
> chore(DAM): update Canto plugin

- Dockerfile
Removed `plugins` nested folder ref in Dockerfile
> Removing `plugins` nested folder ref in Dockerfile

- api/config/app.php
- api/config/app.web.php
> Increased queue job timeout

- api/config/app.php
- api/config/app.web.php
Make queue job TTR setting an env var
> Make queue job TTR setting an env var

- api/config/project/entryTypes/educatorPages--9d045432-a0fb-4fcd-8bca-3bc93b1f7056.yaml
- api/config/project/entryTypes/events--6acd6e24-26c9-4e55-a35b-c29cd36a7a3c.yaml
- api/config/project/entryTypes/pages--23eda090-7e8e-401d-ab49-ee4becc34935.yaml
- api/config/project/entryTypes/post--4729ad5e-485e-4f98-995d-79fa5254cd42.yaml
- api/config/project/entryTypes/studentPages--26ca2777-e4c8-41b4-ac93-aa28d09117dd.yaml
- api/config/project/project.yaml
Remove `featuredImage` from all entries except for Investigation landing pages
> refactor: remove featuredImage

- api/config/general.php
- docker-compose-local-db.sample.yaml
For client PR: https://github.com/lsst-epo/rubin-obs-client/pull/521
> refactor: update preview mode URL format

- api/composer.lock
> Bumped DAM plugin version

- api/composer.json
- api/composer.lock
Bumped version of Neo plugin from 4.0.7 -> 4.2.15
> Bumped version of Neo plugin from 4.0.7 -> 4.2.15

- api/config/contact-form.php
Added contact-form.php config file
> Added contact-form.php config file

- api/config/contact-form.php
Removed log from contact form config
> Removed log from contact form config

- api/composer.json
- api/composer.lock
Bumped `craft-next-js-builds` plugin version
> Bumped `craft-next-js-builds` plugin version

- api/config/project/project.yaml
Revalidate callouts with next builds plugin
> Revalidate callouts with next builds plugin

- api/config/project/fields/logoLarge--a5f6734f-3e3d-4273-9d1f-2ed243b788e4.yaml
- api/config/project/fields/logoSmall--92a53b2d-879a-4353-a009-d926ead4a2db.yaml
- api/config/project/globalSets/siteInfo--8ccd6c1c-8e9b-44e8-93a9-f62589fb4819.yaml
- api/config/project/project.yaml
New fields for desktop and mobile logos, will not make any visual changes until the client header changes are released.
> feat: logo fields

- .github/workflows/build-and-push.yaml
Updated primary branch name in workflow
> Updated primary branch name in workflow

- .github/workflows/build-and-push.yaml
- README.md
Update GitHub Action workflow to trigger on main branch instead of master
> update branch to main from master

- api/config/project/project.yaml
- api/config/project/sections/galleries--3a8b9653-cdd3-46ce-84b2-d73b5dc4de63.yaml
> refactor: change galleries to structure

- api/composer.json
- api/composer.lock
> dep: update Canto DAM plugin

- api/config/project/fields/description--cd801712-4ba3-4a9c-8fab-0d3e2a58b4eb.yaml
- api/config/project/fields/siteDescription--acbea415-ee80-409c-90e2-90ac546820a6.yaml
- api/config/project/fields/teaser--6ed14c66-fec8-4bca-8f29-02cbd1620d12.yaml
- api/config/project/project.yaml
> docs: update instructions for description

- api/config/general.php
> Re-enabled GraphQL caching

- api/config/project/fields/linkedImageList--5fbdc1b8-2968-429d-8f22-e3a9f61e4204.yaml
- api/config/project/matrixBlockTypes/linkedImage--4785e5ad-d948-4c3d-a89c-5e006b4c88b2.yaml
- api/config/project/neo/orders/72e5075a-9b06-4674-b040-615f4a6f7b70.yaml
- api/config/project/neoBlockTypes/linkedImageList--119c4fba-fa5a-4ff3-b30e-695dfb510298.yaml
- api/config/project/project.yaml
Add a linked image list content block, test with API
> feat: linked image list content block

- api/composer.json
- api/composer.lock
> Updated Craft

- api/config/project/project.yaml
Updated project config schema version
> Updated project config schema version

- api/config/project/entryTypes/pages--23eda090-7e8e-401d-ab49-ee4becc34935.yaml
- api/config/project/fields/fullscreenVideo--5a6ebda4-d9d0-46d5-9a4b-8d3be2d5de0f.yaml
- api/config/project/fields/responsiveAssets--f33e3817-e293-4f55-bbd7-bff898cb45fc.yaml
- api/config/project/fields/videoType--b95ced97-62e2-4203-8776-c3f3199c42e9.yaml
- api/config/project/matrixBlockTypes/asset--0fb2f933-d410-485b-aaa3-4bebae1b2de7.yaml
- api/config/project/neoBlockTypes/video--accc0b97-12f3-43ce-941a-068ab8deb620.yaml
- api/config/project/project.yaml
> feat: full screen popup videos
